version: "3"
services:
  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
      - .env.example
    volumes:
      - ./backend:/backend/
      - /backend/node_modules/argon2

  postgres:
    image: postgres:latest
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    env_file:
      - .env.example
    ports:
      - "5432:5432"

volumes:
  postgres-data:
